### ISSUE TITLE
support for minimal mistakes?

### ISSUE THREAD

**Issue by infominer33** [VincentTam/TestStaticmanLab#33]
Would love to see this. I've tried a number of deploys, and pull-request variants.

I will be happy to fork and deploy my own version, once I can find a way to make this work.

I use that theme on 8 different sites, its robust and suited for a number of projects I work on.. 

I'm no web-dev, but I sure spend enough time in VSCode, and searching through github issues...

The site I'm trying to get going is: 

https://github.com/didecentral/
https://didecentral.com
https://github.com/didecentral/didecentral.github.io/blob/master/_includes/comments-providers/staticman_v2.html
https://github.com/didecentral/didecentral.github.io/blob/master/_includes/comments.html

I already had to change `site.reCaptcha.siteKey` to `site.staticman.reCaptcha.siteKey` to get that to work.. but that didn't make the comments work... in the end there is always a 500 error

```
Request URL:https://staticman3.herokuapp.com/v3/entry/github/didecentral/didecentral.github.io/master/comments
Request method:POST
Remote address:52.48.204.199:443
Status code:
500
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade
```

As an aside, I think if there was a button for fork\deploy to heroku (months ago already) we wouldn't have this problem of button clickers hogging a single instance

I think I'll surf around and see if I can find a minimal mistakes site with working staticman comments... someone somewhere has a working combo of GitHub -Minimal Mistakes- Staticman..

**Comment by VincentTam** [comment]
First of all, thanks for your interest in @staticmanlab.  If you want to get MM + SM in minutes, I suggest forking https://framagit.org/staticman-gitlab-pages/minimal-mistakes-demo.  It's served by [@staticmanlab1](https://framagit.org/staticmanlab1) at the instance for Framagit: https://staticman-frama.herokuapp.com.

The response body is also worth reading.

![Screenshot from 2019-07-08 09-03-42](https://user-images.githubusercontent.com/5748535/60789390-4bf7b200-a15f-11e9-80b5-d89de4c08f63.png)

It doesn't seem to be an error on the side of @staticmanlab.  I've created https://github.com/VincentTam/beautiful-jekyll/pull/25 to see this.

![Screenshot from 2019-07-08 08-54-39](https://user-images.githubusercontent.com/5748535/60789421-603baf00-a15f-11e9-8964-0163887919e9.png)

Reading `rawError.message` more carefully, you'll find out the culprit.

```json
{"message":"path cannot start with a slash","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
```

The leftmost slash in your [Staticman config file's `path`](https://github.com/didecentral/didecentral.github.io/blob/7ccc603543ac62db1d8b9a585c0e7a15a8cc9f07/staticman.yml#L86) caused this failure.

Thanks for feedback for Heroku deployment.  I'm not a big fan of proprietary technologies though.  I might add this button in a month if I've found the energy to do so.

Regarding Staticman's reCATPCHA config, see also:

1. My recent experiment with the functionality: https://github.com/daattali/beautiful-jekyll/pull/514#issuecomment-508817895
2. [My blog post about Staticman's erorrs](https://vincenttam.gitlab.io/post/2018-12-25-staticman-repo-setup-errors/).

**Comment by infominer33** [comment]
I'm so grateful for your response! With the state of development only getting more complex in the past months, it was really a lot to dig through and find you here.

You've provided a ton of useful info!

I'll keep a closer eye on the error messages and look forward to digging in from here!

**Comment by infominer33** [comment]
SO BRILLIANT! Oh man, I don't even remember how many different ways I tried to use staticman yesterday that were all flawed in that simple way. I did learn a lot though, and thanks again for all the helpful info here!

This makes me so happy!

I'm working on a series of [GitHub Pages guides](https://web-work.tools/github-pages-starter-pack/), and aim to find open source\self-hosted solutions for all the things we want in our static sites. 

It takes a lot of time to learn to implement each new feature, because most guides\apps are old.

I'll be sure to feature @staticmanlab prominently in the section on comments, and give you a link, in each guide where I show how to implement comments (because I'm running a few open-source educational organizations, and the guides make it easier to attract contributors).

**Comment by VincentTam** [comment]
> I'm working on a series of [GitHub Pages guides](https://web-work.tools/github-pages-starter-pack/), and aim to find open source\self-hosted solutions for all the things we want in our static sites.

Thanks for your feedback.  I regret that my API instances are hosted on Heroku free dynos for convenience and zero-cost coz I'm not (yet?) a developer.  I feel no guilt using free dynos as the original goal is to test Staticman's GitLab support.  Nonetheless, a free dyno is *never* meant for production purposes.  You may consider other free/open-source (self-)hosting solutions like OpenShift to build a truly open-source commenting service.

I would also like to raise your attention about the possibility of spam (e.g. https://github.com/zinefer/zinefer.github.com/pulls?q=is%3Apr+is%3Aclosed+label%3ASpam).  @statimcanlab doesn't have the energy to explore user-defined Akismet support in https://github.com/eduardoboucas/staticman/pull/195 for the moment.
